# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: VTracker
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Prospective vote count tracking.
twitter_username: jekyllrb
github_username:  jekyll
favicon: faveicon.png

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Development: debug mode setting
#   0 - off
#   1 - on
debug_mode: 0

# Where things are
source:         .
destination:    ./_site
plugins_dir:    _plugins
layouts_dir:    ./_layouts
data_dir:       ./_data
includes_dir:   ./_includes
sass:
  sass_dir:     _sass
  style:        expanded    # [nested|expanded|compact|compressed]
  deploy_style: compressed  # [nested|expanded|compact|compressed]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

# Filtering Content
strict_front_matter: true
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Serving
detach:           false
port:             4000
host:             127.0.0.1
baseurl:          "/vtracker" # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site, e.g. http://example.com
show_dir_listing: false
